### ISSUE TITLE
Add WS connection to server

### ISSUE THREAD

**Issue by misterbastean** [lvl-mattwells/DevsPlayingPoker#19]
This work is for setting up the WebSocket server on the BE to connect to the WS client on the FE.

After going through /join/ABCD the user has been added to the room and is navigated to /room/ABCD. On this page the user will attempt to connect to the WebSocket server. On successful connection a new message will be sent containing the following info:
```ts
interface JoinAction {
   event: "Join";
   userId: string;
   roomCode: string;
}
```
The FE will then listen for any RoomUpdates from the BE as a result of the player list updating.

RoomDetails payload will have the following structure:
```ts
type VoterSelectionDetails = {
  userId: ObjectId;
} & (
  | {
      selection: number;
      confidence: 0 | 1 | 2; // higher number === higher confidence
    }
  | {
      selection: null;
      confidence: null;
    }
);
​
// sent to all users in the room anytime any of these values changes
interface RoomDetails {
  state: "Voting" | "Results";
  moderatorId: ObjectId;
  voters: Array<VoterSelectionDetails>;
}
```

**Comment by lvl-mattwells** [comment]
@misterbastean is this the same as #16 ?

**Comment by misterbastean** [comment]
Lol, yup. Not sure how I missed that :-/
