### ISSUE TITLE
Prod 💣

### ISSUE THREAD

**Issue by lvl-mattwells** [lvl-mattwells/DevsPlayingPoker#20]
Looks like the MIME type for the FE CSS and JS assets are trying to come back as `text/html` for some reason. This wasn't happening on #15.

![image](https://user-images.githubusercontent.com/92868767/180284380-f90133f8-38b9-4363-a32c-3a9a68a52e81.png)
![image](https://user-images.githubusercontent.com/92868767/180284488-49544458-9934-40d3-a492-abb4623854f1.png)

**Comment by sarashunter** [comment]
This seems like it's working for me.  When I go to prod, the page loads as expected with the proper css.

**Comment by lvl-mattwells** [comment]
A hard refresh seemed to fix the issue, but if we can specify the Content-Type on the response to prevent this from happening in the future then I think that'd still be worthwhile. Thoughts?

**Comment by misterbastean** [comment]
Never a bad idea to be specific, so I'm in favor of specifying

**Comment by lvl-mattwells** [comment]
This could just be a caching issue. Perhaps the reason the MIME-type is wrong is that the file it's trying to fetch (index.####.js or whatever) doesn't exist. Not really sure how we could invalidate the cache in that scenario 🤔.

**Comment by lvl-mattwells** [comment]
Closing this issue for now since I'm not sure if there's anything we can do about it atm. Plus it's a pretty easy fix to just hard-refresh. Can be opened if it becomes more of an issue later on.
