### ISSUE TITLE
Moderator: Add link to ticket

### ISSUE THREAD

**Issue by lvl-mattwells** [lvl-mattwells/DevsPlayingPoker#41]
When efforting a ticket a scrum master may want to share a link to the ticket so that voters can pull it up on their end.

 - Need BE ticket (adding link to room object)
 - Need FE ticket (adding UI for moderator to set the URL and display to voters)

**Comment by mattwells19** [comment]
Also consider adding support for "x number of days or less" for right sizing that allows the moderator to specify "x" before voting.

Should it honestly just be a free text input? Let the moderator put whatever they want there as like an announcement?

Need a strategy for safely handling URLs. Maybe a dialog to ask the user to confirm navigating to the link?

**Comment by lvl-mattwells** [comment]
Maybe just a label that says: "Voting on:" and then show whatever the moderator wants to add. Hide the label if the moderator doesn't put anything. Need controls for editing/clearing the value as the moderator.
