### ISSUE TITLE
Moderator: Transfer moderator duties

### ISSUE THREAD

**Issue by sarashunter** [lvl-mattwells/DevsPlayingPoker#47]

**Comment by lvl-mattwells** [comment]
Maybe something like this?
https://www.figma.com/file/sVGGiOLzotWDxqvM9Usypv/Wireframes?node-id=135%3A126
![image](https://user-images.githubusercontent.com/92868767/185007381-f10211d0-551d-4ee4-8ad5-af5366c32c2d.png)
